# Generated by Django 5.0.4 on 2024-10-09 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adelanto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Monto', models.IntegerField()),
                ('FechaAdelanto', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('FechaContratacion', models.DateField()),
                ('TurnoChoice', models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Completa', 'Completa')], default='', max_length=8)),
                ('sueldo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmpAde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can', models.IntegerField()),
                ('ade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vete.adelanto')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vete.empleado')),
            ],
        ),
    ]
