# Generated by Django 5.0.4 on 2024-10-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vete', '0003_proveedore_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='tipo_mascota',
            field=models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato')], default=None, max_length=5),
            preserve_default=False,
        ),
    ]
