# Generated by Django 5.0.4 on 2024-12-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vete', '0008_alter_detalleventa_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gmail', models.CharField(max_length=125)),
            ],
        ),
    ]
