# Generated by Django 5.0.4 on 2024-12-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vete', '0009_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='Content',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='subscription',
            name='asunto',
            field=models.CharField(default='', max_length=200),
        ),
    ]
