# Generated by Django 5.0.4 on 2025-02-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vete', '0010_subscription_content_subscription_asunto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='Content',
        ),
        migrations.AddField(
            model_name='subscription',
            name='Nombre',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
