# Generated by Django 5.0.4 on 2025-03-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vete', '0011_remove_subscription_content_subscription_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='delete',
            field=models.BooleanField(default=True),
        ),
    ]
