# Generated by Django 5.0.4 on 2025-03-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vete', '0013_alter_articulo_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='delete',
            new_name='delete_1',
        ),
        migrations.AddField(
            model_name='cliente',
            name='delete_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empleado',
            name='delete_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mascota',
            name='delete_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proveedore',
            name='delete_1',
            field=models.BooleanField(default=False),
        ),
    ]
